

-- Create a new database named SampleDB
--CREATE DATABASE BioTIME;
--GO

-- Optionally, switch to the new database
USE BioTIME;
GO


DROP TABLE IF EXISTS dbo.obs_summary;



CREATE TABLE  dbo.obs_summary 
(
    ID NVARCHAR(100),
    STUDYID NVARCHAR(100),
    BDAY NVARCHAR(10),
    BMONTH NVARCHAR(100),
    BYEAR NVARCHAR(100),
    SAMPLE_DESC  NVARCHAR(100),
    PLOT NVARCHAR(100),
    ID_SPECIES NVARCHAR(100),
    LATITUDE NVARCHAR(100),
    LONGITUDE NVARCHAR(100),
    SUM_ABUNDANCE NVARCHAR(100),
    SUM_BIOMASS NVARCHAR(100),
    GENUS  NVARCHAR(100),
    SPECIES  NVARCHAR(100),
    GENUS_SPECIES  NVARCHAR(500)
);
GO



BULK INSERT dbo.obs_summary
FROM 'C:\Users\GRowell\work\Databases\BioTIME\BioTIMEQuery_24_06_2021.csv'
WITH (
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '\n'
);


